services:
  - type: web
    name: personal-finance-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GROQ_API_KEY
        sync: false
    config:
      maxBodySize: "10M"
      timeoutSeconds: 120
